[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#DA7756"
backgroundColor = "#1F1E1D"
secondaryBackgroundColor = "#171716"
textColor = "#ECEBE8"
font = "sans serif"